configuration: Debug
image: Visual Studio 2017

environment:
  app_version: '7.2.0'

version: '%app_version%.{build}'

assembly_info:
  patch: true
  file: SolutionInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"	

cache:
  packages -> **\packages.config  

before_build:
  - nuget sources add -name bddhelper -source https://ci.appveyor.com/nuget/ospsuite-bddhelper 
  - nuget sources add -name utility -source https://ci.appveyor.com/nuget/ospsuite-utility 
  - nuget sources add -name serializer -source https://ci.appveyor.com/nuget/ospsuite-serializer 
  - nuget sources add -name databinding -source https://ci.appveyor.com/nuget/ospsuite-databinding 
  - nuget sources add -name texreporting -source https://ci.appveyor.com/nuget/ospsuite-texreporting 
  - nuget sources add -name databinding-devexpress -source https://ci.appveyor.com/nuget/ospsuite-databinding-devexpress 
  - nuget sources add -name funcparser -source https://ci.appveyor.com/nuget/ospsuite-funcparser 
  - nuget sources add -name simmodel -source https://ci.appveyor.com/nuget/ospsuite-simmodel
  - nuget sources add -name cvodes -source https://ci.appveyor.com/nuget/ospsuite-simmodel-solver-cvodes-282
  - nuget sources add -name smartxls -source https://ci.appveyor.com/nuget/ospsuite-smartxls
  - nuget restore

build:
  verbosity: minimal
  project: OSPSuite.Core.sln

test_script:
  - rake cover

install:  
 - set PATH=C:\Ruby22\bin;C:\\Python34;C:\\Python34\\Scripts;%PATH%"
 - pip install codecov
 - git submodule update --init --recursive
 - ps: >-
    (new-object net.webclient).DownloadFile('https://download.microsoft.com/download/A/2/D/A2D8587D-0027-4217-9DAD-38AFDB0A177E/msxml.msi', 'C:\\msxml.msi')

    Start-Process msiexec.exe -ArgumentList /i, C:\msxml.msi, /quiet, /qn, /norestart -Wait
