name: 'Cover with JetBrains dotCover'
description: 'Install and run JetBrains dotcover with an xml configuration'
author: 'Robert McIntosh'

inputs:
  xml-configuration:
    description: 'The xml file that configures the dotCover covearage'
    required: true
  token:
    description: the codecov.io upload token
    required: true

runs:
  using: "composite"
  steps:
    - id: install-prerequisites
      run: |
        dotnet tool install --global JetBrains.dotCover.CommandLineTools --version 2024.3.5
        nuget install NUnit.ConsoleRunner -Version 3.19.2 -DirectDownload -OutputDirectory .
      shell: powershell
    
    - id: run-tests
      run: dotnet dotcover cover ${{ inputs.xml-configuration }} --targetExecutable=./NUnit.ConsoleRunner.3.19.2/tools/nunit3-console.exe --output=coverageReport.xml --reportType=DetailedXML -- test --no-build
      shell: powershell

    - uses: codecov/codecov-action@v5
      with:
        fail_ci_if_error: true
        files: ./coverageReport.xml
        token: ${{ inputs.token }}
        verbose: true