<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Version Condition="'$(Version)' == ''">13.0.0</Version>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="OSPSuite.Utility" Version="5.0.0.12" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\OSPSuite.Assets\OSPSuite.Assets.csproj" />
		<ProjectReference Include="..\OSPSuite.Core\OSPSuite.Core.csproj" />
		<ProjectReference Include="..\OSPSuite.Infrastructure.Autofac\OSPSuite.Infrastructure.Autofac.csproj" />
		<ProjectReference Include="..\OSPSuite.Infrastructure.Import\OSPSuite.Infrastructure.Import.csproj" />
		<ProjectReference Include="..\OSPSuite.Infrastructure.Serialization\OSPSuite.Infrastructure.Serialization.csproj" />
		<ProjectReference Include="..\OSPSuite.Infrastructure\OSPSuite.Infrastructure.csproj" />
	</ItemGroup>
</Project>
